export const APP_SET_USER = 'APP_SET_USER'
export const APP_STORE_USER = 'APP_STORE_USER'
export const APP_GET_USER = 'APP_GET_USER'
export const APP_GET_USER_FAILURE = 'APP_GET_USER_FAILURE'

export const APP_LOGOUT_REQUEST = 'APP_LOGOUT_REQUEST'
export const APP_LOGOUT_FAILURE = 'APP_LOGOUT_FAILURE'
export const APP_LOGOUT_SUCCESS = 'APP_LOGOUT_SUCCESS'

export const APP_ERROR = 'APP_ERROR'